# Generated by Django 4.2 on 2026-05-18 16:40

from django.conf import settings  # Importa nombres concretos desde un módulo.
import django.contrib.auth.models  # Importa un módulo de Python.
import django.contrib.auth.validators  # Importa un módulo de Python.
from django.db import migrations, models  # Importa nombres concretos desde un módulo.
import django.db.models.deletion  # Importa un módulo de Python.
import django.utils.timezone  # Importa un módulo de Python.


class Migration(migrations.Migration):  # Define una clase Python.

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),  # Define un campo de texto corto en el modelo.
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),  # Define un campo que almacena fecha y hora.
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),  # Define un campo de texto corto en el modelo.
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),  # Define un campo de texto corto en el modelo.
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),  # Define un campo de texto corto en el modelo.
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),  # Define un campo que almacena fecha y hora.
                ('rol', models.CharField(choices=[('anfitrion', 'Anfitrión'), ('huesped', 'Huésped'), ('admin', 'Administrador')], default='huesped', max_length=20)),  # Define un campo de texto corto en el modelo.
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),  # Define un campo de texto corto en el modelo.
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),  # Define un campo que almacena fecha y hora.
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='usuario_groups', to='auth.group', verbose_name='groups')),  # Define una relación de muchos a muchos entre modelos.
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usuario_permissions', to='auth.permission', verbose_name='user permissions')),  # Define una relación de muchos a muchos entre modelos.
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-fecha_registro'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),  # Define un campo de texto corto en el modelo.
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),  # Define un campo de texto corto en el modelo.
                ('descripcion', models.TextField()),  # Define un campo de texto largo en el modelo.
                ('ubicacion', models.CharField(max_length=255)),  # Define un campo de texto corto en el modelo.
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=10)),  # Define un campo numérico decimal para precios u importes.
                ('precio_fin_semana', models.DecimalField(decimal_places=2, max_digits=10)),  # Define un campo numérico decimal para precios u importes.
                ('tarifa_limpieza', models.DecimalField(decimal_places=2, default=0, max_digits=10)),  # Define un campo numérico decimal para precios u importes.
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('mantenimiento', 'Mantenimiento'), ('retirada', 'Retirada')], default='disponible', max_length=20)),  # Define un campo de texto corto en el modelo.
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),  # Define un campo que almacena una fecha.
                ('fecha_fin', models.DateField()),  # Define un campo que almacena una fecha.
                ('cantidad_huespedes', models.IntegerField()),  # Define un campo entero.
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20)),  # Define un campo de texto corto en el modelo.
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=12)),  # Define un campo numérico decimal para precios u importes.
                ('id_huesped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),  # Define una relación de clave foránea entre modelos.
                ('id_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='presupuesto.propiedad')),  # Define una relación de clave foránea entre modelos.
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PropiedadAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuesto.amenity')),  # Define una relación de clave foránea entre modelos.
                ('id_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuesto.propiedad')),  # Define una relación de clave foránea entre modelos.
            ],
            options={
                'verbose_name': 'Propiedad Amenity',
                'verbose_name_plural': 'Propiedades Amenities',
                'unique_together': {('id_propiedad', 'id_amenity')},
            },
        ),
        migrations.AddField(
            model_name='propiedad',
            name='amenities',
            field=models.ManyToManyField(through='presupuesto.PropiedadAmenity', to='presupuesto.amenity'),  # Define una relación de muchos a muchos entre modelos.
        ),
        migrations.AddField(
            model_name='propiedad',
            name='id_anfitrion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to=settings.AUTH_USER_MODEL),  # Define una relación de clave foránea entre modelos.
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),  # Define un campo de texto largo en el modelo.
                ('estado', models.CharField(choices=[('no_leida', 'No Leída'), ('leida', 'Leída'), ('archivada', 'Archivada')], default='no_leida', max_length=20)),  # Define un campo de texto corto en el modelo.
                ('fecha', models.DateTimeField(auto_now_add=True)),  # Define un campo que almacena fecha y hora.
                ('id_reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='presupuesto.reserva')),  # Define una relación de clave foránea entre modelos.
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),  # Define una relación de clave foránea entre modelos.
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(choices=[(1, '⭐ Muy Malo'), (2, '⭐⭐ Malo'), (3, '⭐⭐⭐ Regular'), (4, '⭐⭐⭐⭐ Bueno'), (5, '⭐⭐⭐⭐⭐ Excelente')])),  # Define un campo entero.
                ('comentario', models.TextField()),  # Define un campo de texto largo en el modelo.
                ('fecha', models.DateTimeField(auto_now_add=True)),  # Define un campo que almacena fecha y hora.
                ('id_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='presupuesto.propiedad')),  # Define una relación de clave foránea entre modelos.
                ('id_reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='presupuesto.reserva')),  # Define una relación uno a uno entre modelos.
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),  # Define una relación de clave foránea entre modelos.
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-fecha'],
                'unique_together': {('id_reserva', 'id_propiedad')},
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),  # Define un campo que almacena una fecha.
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('bloqueada', 'Bloqueada')], default='disponible', max_length=20)),  # Define un campo de texto corto en el modelo.
                ('id_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='presupuesto.propiedad')),  # Define una relación de clave foránea entre modelos.
            ],
            options={
                'verbose_name': 'Disponibilidad',
                'verbose_name_plural': 'Disponibilidades',
                'ordering': ['fecha'],
                'unique_together': {('id_propiedad', 'fecha')},
            },
        ),
    ]
