# Generated by Django 4.2 on 2026-06-17 14:21

from django.db import migrations, models
import django.db.models.deletion


def link_existing_reserved_dates(apps, schema_editor):
    Disponibilidad = apps.get_model('presupuesto', 'Disponibilidad')
    Reserva = apps.get_model('presupuesto', 'Reserva')

    reserved_dates = Disponibilidad.objects.filter(estado='reservada', id_reserva__isnull=True)
    for disponibilidad in reserved_dates:
        reserva = (
            Reserva.objects.filter(
                id_propiedad_id=disponibilidad.id_propiedad_id,
                fecha_inicio__lte=disponibilidad.fecha,
                fecha_fin__gt=disponibilidad.fecha,
                estado__in=['pendiente', 'confirmada'],
            )
            .order_by('-fecha_inicio')
            .first()
        )
        if reserva:
            disponibilidad.id_reserva_id = reserva.id
            disponibilidad.fecha_inicio_reserva = reserva.fecha_inicio
            disponibilidad.save(update_fields=['id_reserva', 'fecha_inicio_reserva'])


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0004_normalize_amenity_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disponibilidad',
            options={'verbose_name': 'Disponibilidad', 'verbose_name_plural': 'Disponibilidades'},
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='id_reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disponibilidades', to='presupuesto.reserva'),
        ),
        migrations.RunPython(link_existing_reserved_dates, migrations.RunPython.noop),
    ]
