# Generated by Django 4.2 on 2026-06-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0005_alter_disponibilidad_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name': 'Amenity', 'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'verbose_name': 'Notificacion', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='propiedad',
            options={'verbose_name': 'Propiedad', 'verbose_name_plural': 'Propiedades'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Reseña', 'verbose_name_plural': 'Reseñas'},
        ),
    ]
