# Generated by Django 4.2 on 2026-06-17 14:42

from django.db import migrations, models


SYSTEM_PROMPT = """
Sos el asistente de reservas de GuairaDevs Booking. Ayudas a huespedes a consultar
propiedades, amenities, resenas, disponibilidad y reservas; y ayudas a anfitriones a revisar
sus reservas. No respondes temas fuera de la plataforma. No buscas online: solo usas
la informacion disponible en la API/backend del proyecto. Si falta un dato, lo pedis.
Antes de crear, confirmar, cancelar o modificar una reserva, siempre pedis confirmacion
explicita y mostras el resumen de la accion.
""".strip()


def create_default_agent_config(apps, schema_editor):
    AgenteIAConfig = apps.get_model('presupuesto', 'AgenteIAConfig')
    AgenteIAConfig.objects.update_or_create(
        nombre='Agente IA de Booking',
        defaults={
            'descripcion': (
                'Asistente para huespedes y anfitriones. Consulta propiedades, amenities, '
                'resenas, disponibilidad y reservas usando datos reales del backend.'
            ),
            'system_prompt': SYSTEM_PROMPT,
            'endpoint_chat': '/api/agent/chat/',
            'endpoint_disponibilidad': '/api/availability/',
            'endpoint_reservas': '/api/reservations/',
            'endpoint_propiedades': '/api/properties/',
            'requiere_confirmacion_reserva': True,
            'activo': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0006_alter_amenity_options_alter_notificacion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteIAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Agente IA de Booking', max_length=100)),
                ('descripcion', models.TextField(default='Asistente para huespedes y anfitriones. Consulta propiedades, amenities, resenas, disponibilidad y reservas usando datos reales del backend.')),
                ('system_prompt', models.TextField()),
                ('endpoint_chat', models.CharField(default='/api/agent/chat/', max_length=150)),
                ('endpoint_disponibilidad', models.CharField(default='/api/availability/', max_length=150)),
                ('endpoint_reservas', models.CharField(default='/api/reservations/', max_length=150)),
                ('endpoint_propiedades', models.CharField(default='/api/properties/', max_length=150)),
                ('requiere_confirmacion_reserva', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agente IA',
                'verbose_name_plural': 'Agente IA',
            },
        ),
        migrations.RunPython(create_default_agent_config, migrations.RunPython.noop),
    ]
