# Generated by Django 4.2 on 2026-06-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0007_agenteiaconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntarIA',
            fields=[
            ],
            options={
                'verbose_name': 'Preguntar a la IA',
                'verbose_name_plural': 'Preguntar a la IA',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('presupuesto.agenteiaconfig',),
        ),
    ]
