# Generated by Django 4.2 on 2026-06-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0008_preguntaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='precio_fin_semana',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Precio fin de semana (Gs.)'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='precio_noche',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Precio noche (Gs.)'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tarifa_limpieza',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tarifa limpieza (Gs.)'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='precio_total',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Precio total (Gs.)'),
        ),
    ]
