# Generated by Django 4.2 on 2026-06-30 23:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0009_alter_propiedad_precio_fin_semana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='capacidad_maxima_huespedes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='permite_fiestas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='permite_fumar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='permite_mascotas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipo_alojamiento',
            field=models.CharField(choices=[('casa_entera', 'Casa entera'), ('habitacion_privada', 'Habitacion privada'), ('habitacion_compartida', 'Habitacion compartida')], default='casa_entera', max_length=30),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('activa', 'Activa'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='PropiedadFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(upload_to='propiedades/fotos/')),
                ('descripcion', models.CharField(blank=True, default='', max_length=150)),
                ('es_portada', models.BooleanField(default=False)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='presupuesto.propiedad')),
            ],
            options={
                'verbose_name': 'Foto de propiedad',
                'verbose_name_plural': 'Fotos de propiedades',
                'ordering': ['-es_portada', 'id'],
            },
        ),
    ]
