# Generated by Django 4.2 on 2026-06-30 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0010_propiedad_capacidad_maxima_huespedes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='politica_cancelacion',
            field=models.CharField(choices=[('flexible', 'Flexible'), ('moderada', 'Moderada'), ('estricta', 'Estricta')], default='moderada', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cancelada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_canceladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='monto_reembolso',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Reembolso simulado (Gs.)'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='HistorialPropiedadVisitada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateTimeField(default=django.utils.timezone.now)),
                ('cantidad_visitas', models.PositiveIntegerField(default=1)),
                ('id_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='presupuesto.propiedad')),
                ('id_usuario', models.ForeignKey(limit_choices_to={'rol': 'huesped'}, on_delete=django.db.models.deletion.CASCADE, related_name='historial_propiedades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de propiedad visitada',
                'verbose_name_plural': 'Historial de propiedades visitadas',
                'ordering': ['-fecha_visita'],
                'unique_together': {('id_usuario', 'id_propiedad')},
            },
        ),
    ]
